sudo: false

language: c

compiler:
    - gcc
    - clang

matrix:
    include:
        - compiler: gcc
          env: COVERAGE="--disable-valgrind --enable-gcov"

addons:
    apt:
        packages:
            - libonig-dev
            - valgrind

before_install:
    - rm lexer.h lexer.c parser.h parser.c

install:
    - bundle install --gemfile=docs/Gemfile

    - wget http://ftp.debian.org/debian/pool/main/b/bison/bison_3.0.2.dfsg-2_amd64.deb
    - ar p bison_3.0.2.dfsg-2_amd64.deb data.tar.xz | tar xJ

    - if [ -n "$COVERAGE" ]; then pip install --user cpp-coveralls; fi

before_script:
    - autoreconf -i
    - ./configure
        YACC="usr/bin/bison -y"
        $COVERAGE

script:
    - make -j4 BISON_PKGDATADIR=$(pwd)/usr/share/bison
    - make check -j4

after_script:
    - |
        if [ -n "$COVERAGE" ]; then
            rm -rf .libs usr # don't care about coverage for libjq and bison
            coveralls -e lexer.c -e parser.c -e jv_dtoa.c --gcov-options '\-lp'
        fi

after_failure:
    - cat test-suite.log
    - cat tests/*.log

notifications:
    email: false
